### ISSUE TITLE
Auto resizing of text for Sentence View doesn't work in Android

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora-expo#3]

**Comment by allan-walker** [comment]
@kmahelona it seems to work on iOS by just truncating the sentence - this presumably isn't a great solution as the user can't read the full sentence while recording

![screen shot 2018-09-01 at 2 03 30 pm](https://user-images.githubusercontent.com/4606323/44941357-d4931c80-adef-11e8-8d89-6a694bac2470.png)

**Comment by allan-walker** [comment]
Ok, cool. `adjustsFontSizeToFit` is just an iOS property anyway, so I will implement a cross-platform solution.

**Comment by kmahelona** [comment]
@allan-walker this is working nicely. Is it possible to set a min font size on your solution? At least up to a certain point e.g. if min causes overflow we might have to go smaller?

**Comment by allan-walker** [comment]
Yeah we can definitely set a min - what would you like it to be? @kmahelona 

The only issue is trying to work out if it causes an overflow and then going smaller. I'm not too sure how we could easily determine the overflow - we could take a best guess based on character count, but that doesn't take word-length and line-count into account. My instinct would be to delay this until after launch because I couldn't tell you how long that might take to come up with a solution.

**Comment by kmahelona** [comment]
Okay, let's start win a min font size. I think it was about 30pt before. Let's got with 28pt.

To handle overflow for now I'll only serve shorter sentences to the app from the backend. There are some really long ones that I don't think should even be there for our purposes but it is what it is.

**Comment by kmahelona** [comment]
Fixed in https://github.com/TeHikuMedia/corpora-expo/releases/tag/v1.0.2
